In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
# Torch Tensors:

In [ ]:
from __future__ import print_function

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
y = torch.rand(5,3)

In [12]:
y

tensor([[0.9774, 0.6172, 0.1735],
        [0.2571, 0.7933, 0.9957],
        [0.0247, 0.2143, 0.5865],
        [0.7914, 0.9246, 0.5829],
        [0.5859, 0.5919, 0.8871]])

In [13]:
z = torch.zeros(5, 3, dtype=torch.long)

In [15]:
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [16]:
x = torch.tensor([5.5, 3])

In [17]:
x

tensor([5.5000, 3.0000])

In [23]:
x = x.new_ones(5, 3, dtype=torch.double)

In [19]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [26]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.2396, -1.1765, -0.5567],
        [ 0.5209, -1.3766, -1.1383],
        [-1.8674, -1.5575,  0.5924],
        [ 2.5142, -0.7658, -0.1000],
        [ 0.9632, -0.9638, -0.7100]])


In [27]:
x

tensor([[-0.2396, -1.1765, -0.5567],
        [ 0.5209, -1.3766, -1.1383],
        [-1.8674, -1.5575,  0.5924],
        [ 2.5142, -0.7658, -0.1000],
        [ 0.9632, -0.9638, -0.7100]])

In [28]:
y = torch.rand(5,3)

In [29]:
y

tensor([[0.1489, 0.6941, 0.8443],
        [0.3753, 0.7862, 0.8915],
        [0.5427, 0.0311, 0.9951],
        [0.6099, 0.6436, 0.5447],
        [0.5020, 0.1731, 0.2087]])

In [33]:
print(x+y)

tensor([[-0.0907, -0.4823,  0.2876],
        [ 0.8962, -0.5905, -0.2468],
        [-1.3248, -1.5265,  1.5875],
        [ 3.1241, -0.1222,  0.4447],
        [ 1.4652, -0.7907, -0.5014]])


In [34]:
print(torch.add(x,y))

tensor([[-0.0907, -0.4823,  0.2876],
        [ 0.8962, -0.5905, -0.2468],
        [-1.3248, -1.5265,  1.5875],
        [ 3.1241, -0.1222,  0.4447],
        [ 1.4652, -0.7907, -0.5014]])


In [35]:
# Addition: providing an output tensor as argument

In [43]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0907, -0.4823,  0.2876],
        [ 0.8962, -0.5905, -0.2468],
        [-1.3248, -1.5265,  1.5875],
        [ 3.1241, -0.1222,  0.4447],
        [ 1.4652, -0.7907, -0.5014]])


In [44]:
y

tensor([[0.1489, 0.6941, 0.8443],
        [0.3753, 0.7862, 0.8915],
        [0.5427, 0.0311, 0.9951],
        [0.6099, 0.6436, 0.5447],
        [0.5020, 0.1731, 0.2087]])

In [45]:
x

tensor([[-0.2396, -1.1765, -0.5567],
        [ 0.5209, -1.3766, -1.1383],
        [-1.8674, -1.5575,  0.5924],
        [ 2.5142, -0.7658, -0.1000],
        [ 0.9632, -0.9638, -0.7100]])

In [46]:
y.add_(x)

tensor([[-0.0907, -0.4823,  0.2876],
        [ 0.8962, -0.5905, -0.2468],
        [-1.3248, -1.5265,  1.5875],
        [ 3.1241, -0.1222,  0.4447],
        [ 1.4652, -0.7907, -0.5014]])

In [47]:
#You can use standard NumPy-like indexing with all bells and whistles!

In [48]:
x

tensor([[-0.2396, -1.1765, -0.5567],
        [ 0.5209, -1.3766, -1.1383],
        [-1.8674, -1.5575,  0.5924],
        [ 2.5142, -0.7658, -0.1000],
        [ 0.9632, -0.9638, -0.7100]])

In [49]:
print(x[:, 1])

tensor([-1.1765, -1.3766, -1.5575, -0.7658, -0.9638])


In [58]:
x

tensor([[-0.2396, -1.1765, -0.5567],
        [ 0.5209, -1.3766, -1.1383],
        [-1.8674, -1.5575,  0.5924],
        [ 2.5142, -0.7658, -0.1000],
        [ 0.9632, -0.9638, -0.7100]])

In [59]:
# If you want to resize/reshape tensor, you can use torch.view:

In [60]:
x = torch.randn(4, 4)

In [65]:
x

tensor([[ 1.2407,  1.2659, -1.6467,  1.2745],
        [ 0.0675,  1.0656,  0.8495,  1.3648],
        [-1.2873, -1.2192, -0.5811, -0.1221],
        [-0.0330,  0.5821,  0.5651,  0.0630]])

In [67]:
y = x.view(16)

In [68]:
y

tensor([ 1.2407,  1.2659, -1.6467,  1.2745,  0.0675,  1.0656,  0.8495,  1.3648,
        -1.2873, -1.2192, -0.5811, -0.1221, -0.0330,  0.5821,  0.5651,  0.0630])

In [75]:
z = x.view(-1, 8)

In [76]:
z

tensor([[ 1.2407,  1.2659, -1.6467,  1.2745,  0.0675,  1.0656,  0.8495,  1.3648],
        [-1.2873, -1.2192, -0.5811, -0.1221, -0.0330,  0.5821,  0.5651,  0.0630]])

In [77]:
z = x.view(-1, 2)

In [78]:
z

tensor([[ 1.2407,  1.2659],
        [-1.6467,  1.2745],
        [ 0.0675,  1.0656],
        [ 0.8495,  1.3648],
        [-1.2873, -1.2192],
        [-0.5811, -0.1221],
        [-0.0330,  0.5821],
        [ 0.5651,  0.0630]])

In [79]:
# If you have a one element tensor, use .item() to get the value as a Python number

In [80]:
x

tensor([[ 1.2407,  1.2659, -1.6467,  1.2745],
        [ 0.0675,  1.0656,  0.8495,  1.3648],
        [-1.2873, -1.2192, -0.5811, -0.1221],
        [-0.0330,  0.5821,  0.5651,  0.0630]])

In [87]:
x = torch.randn(1)


In [88]:
x

tensor([0.0529])

In [89]:
x

tensor([0.0529])

In [90]:
print(x.item())

0.05288035422563553


In [91]:
# NumPy Bridge:

In [96]:
a = torch.ones(5)

In [97]:
a

tensor([1., 1., 1., 1., 1.])

In [98]:
b = a.numpy()

In [99]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [100]:
# Converting NumPy Array to Torch Tensor

In [102]:
import numpy as np
a = np.ones(5)

In [112]:
a

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [113]:
type(a)

torch.Tensor

In [120]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
# np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
