In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
# Torch Tensors:

In [4]:
from __future__ import print_function

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[-5.6132e-38,  4.5687e-41,  3.2826e-35],
        [ 3.0658e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [6]:
y = torch.rand(5,3)

In [7]:
y

tensor([[0.0645, 0.6832, 0.1593],
        [0.4620, 0.1064, 0.0271],
        [0.0817, 0.5350, 0.6626],
        [0.6685, 0.1412, 0.4015],
        [0.1484, 0.3044, 0.8186]])

In [8]:
z = torch.zeros(5, 3, dtype=torch.long)

In [9]:
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])

In [11]:
x

tensor([5.5000, 3.0000])

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)

In [13]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.6425,  0.1579,  0.0569],
        [-0.5905,  0.8638,  1.0510],
        [-1.2488,  1.4561, -1.0840],
        [ 0.5981, -1.0687,  1.1854],
        [-1.0852,  2.8776, -0.5652]])


In [15]:
x

tensor([[-0.6425,  0.1579,  0.0569],
        [-0.5905,  0.8638,  1.0510],
        [-1.2488,  1.4561, -1.0840],
        [ 0.5981, -1.0687,  1.1854],
        [-1.0852,  2.8776, -0.5652]])

In [16]:
y = torch.rand(5,3)

In [17]:
y

tensor([[0.7004, 0.5938, 0.2513],
        [0.0222, 0.7992, 0.4229],
        [0.7622, 0.5970, 0.4770],
        [0.0816, 0.3814, 0.4035],
        [0.4864, 0.7736, 0.2780]])

In [18]:
print(x+y)

tensor([[ 0.0579,  0.7517,  0.3082],
        [-0.5683,  1.6630,  1.4739],
        [-0.4866,  2.0531, -0.6070],
        [ 0.6797, -0.6874,  1.5890],
        [-0.5988,  3.6512, -0.2872]])


In [19]:
print(torch.add(x,y))

tensor([[ 0.0579,  0.7517,  0.3082],
        [-0.5683,  1.6630,  1.4739],
        [-0.4866,  2.0531, -0.6070],
        [ 0.6797, -0.6874,  1.5890],
        [-0.5988,  3.6512, -0.2872]])


In [20]:
# Addition: providing an output tensor as argument

In [21]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0579,  0.7517,  0.3082],
        [-0.5683,  1.6630,  1.4739],
        [-0.4866,  2.0531, -0.6070],
        [ 0.6797, -0.6874,  1.5890],
        [-0.5988,  3.6512, -0.2872]])


In [22]:
y

tensor([[0.7004, 0.5938, 0.2513],
        [0.0222, 0.7992, 0.4229],
        [0.7622, 0.5970, 0.4770],
        [0.0816, 0.3814, 0.4035],
        [0.4864, 0.7736, 0.2780]])

In [23]:
x

tensor([[-0.6425,  0.1579,  0.0569],
        [-0.5905,  0.8638,  1.0510],
        [-1.2488,  1.4561, -1.0840],
        [ 0.5981, -1.0687,  1.1854],
        [-1.0852,  2.8776, -0.5652]])

In [24]:
y.add_(x)

tensor([[ 0.0579,  0.7517,  0.3082],
        [-0.5683,  1.6630,  1.4739],
        [-0.4866,  2.0531, -0.6070],
        [ 0.6797, -0.6874,  1.5890],
        [-0.5988,  3.6512, -0.2872]])

In [25]:
#You can use standard NumPy-like indexing with all bells and whistles!

In [26]:
x

tensor([[-0.6425,  0.1579,  0.0569],
        [-0.5905,  0.8638,  1.0510],
        [-1.2488,  1.4561, -1.0840],
        [ 0.5981, -1.0687,  1.1854],
        [-1.0852,  2.8776, -0.5652]])

In [27]:
print(x[:, 1])

tensor([ 0.1579,  0.8638,  1.4561, -1.0687,  2.8776])


In [28]:
x

tensor([[-0.6425,  0.1579,  0.0569],
        [-0.5905,  0.8638,  1.0510],
        [-1.2488,  1.4561, -1.0840],
        [ 0.5981, -1.0687,  1.1854],
        [-1.0852,  2.8776, -0.5652]])

In [29]:
# If you want to resize/reshape tensor, you can use torch.view:

In [30]:
x = torch.randn(4, 4)

In [31]:
x

tensor([[ 1.9354, -0.1771,  0.8004, -1.1321],
        [-1.6326, -0.9473,  0.2896,  1.2419],
        [-0.1709, -3.3337, -0.2815,  0.5517],
        [ 0.1059,  0.7526,  1.2502, -0.3637]])

In [32]:
y = x.view(16)

In [33]:
y

tensor([ 1.9354, -0.1771,  0.8004, -1.1321, -1.6326, -0.9473,  0.2896,  1.2419,
        -0.1709, -3.3337, -0.2815,  0.5517,  0.1059,  0.7526,  1.2502, -0.3637])

In [34]:
z = x.view(-1, 8)

In [35]:
z

tensor([[ 1.9354, -0.1771,  0.8004, -1.1321, -1.6326, -0.9473,  0.2896,  1.2419],
        [-0.1709, -3.3337, -0.2815,  0.5517,  0.1059,  0.7526,  1.2502, -0.3637]])

In [36]:
z = x.view(-1, 2)

In [37]:
z

tensor([[ 1.9354, -0.1771],
        [ 0.8004, -1.1321],
        [-1.6326, -0.9473],
        [ 0.2896,  1.2419],
        [-0.1709, -3.3337],
        [-0.2815,  0.5517],
        [ 0.1059,  0.7526],
        [ 1.2502, -0.3637]])

In [38]:
# If you have a one element tensor, use .item() to get the value as a Python number

In [39]:
x

tensor([[ 1.9354, -0.1771,  0.8004, -1.1321],
        [-1.6326, -0.9473,  0.2896,  1.2419],
        [-0.1709, -3.3337, -0.2815,  0.5517],
        [ 0.1059,  0.7526,  1.2502, -0.3637]])

In [40]:
x = torch.randn(1)


In [41]:
x

tensor([2.0870])

In [42]:
x

tensor([2.0870])

In [43]:
print(x.item())

2.087033987045288


In [44]:
# NumPy Bridge:

In [45]:
a = torch.ones(5)

In [46]:
a

tensor([1., 1., 1., 1., 1.])

In [47]:
b = a.numpy()

In [48]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [49]:
# Converting NumPy Array to Torch Tensor

In [50]:
import numpy as np
a = np.ones(5)

In [51]:
a

array([1., 1., 1., 1., 1.])

In [52]:
type(a)

numpy.ndarray

In [54]:
import numpy as np

In [55]:
a = np.ones(5)

In [56]:
a

array([1., 1., 1., 1., 1.])

In [57]:
type(a)

numpy.ndarray

In [58]:
b = torch.from_numpy(a)

In [59]:
b 

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [60]:
type(b)

torch.Tensor

In [61]:
# CUDA Tensors Handel:

In [62]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y 

In [69]:
print(z)
print(z.to("cpu",torch.double))

tensor([3.0870], device='cuda:0')
tensor([3.0870], dtype=torch.float64)


In [72]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [73]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [76]:
print(y.grad_fn)

In [77]:
z = y*y*3

In [78]:
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [79]:
print(z.grad_fn)

In [80]:
out = z.mean()

In [83]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [84]:
a = torch.randn(2, 2)

In [87]:
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [88]:
a.requires_grad_(True)

tensor([[  1.8478, -13.4463],
        [  0.0932,  10.8382]], requires_grad=True)

In [89]:
print(a.requires_grad)

True


In [90]:
b = (a * a).sum()

In [91]:
print(b.grad_fn)

In [96]:
# This is a 1d Tensor :
a = torch.tensor([2,2,1])

In [97]:
a

tensor([2, 2, 1])

In [98]:
b = torch.tensor([[2,1,4],[3,5,6],[4,5,9]])

In [99]:
b

tensor([[2, 1, 4],
        [3, 5, 6],
        [4, 5, 9]])

In [100]:
c = torch.FloatTensor([[2,1,6],[4,9,7],[4,8,9]])

In [101]:
c

tensor([[2., 1., 6.],
        [4., 9., 7.],
        [4., 8., 9.]])

In [102]:
type(c)

torch.Tensor

In [103]:
print(c.shape) # atribute

torch.Size([3, 3])


In [105]:
print(c.size()) #

torch.Size([3, 3])


In [109]:
print(c.shape[0])

3


In [120]:
d = torch.DoubleTensor([[2,1,6],[4,12,7],[4,8,9]])

In [121]:
d

tensor([[ 2.,  1.,  6.],
        [ 4., 12.,  7.],
        [ 4.,  8.,  9.]], dtype=torch.float64)

In [122]:
type(d)

torch.Tensor

In [123]:
print(c.mean())

tensor(5.5556)


In [124]:
print(d.mean())

tensor(5.8889, dtype=torch.float64)


In [125]:
print(d.std())

tensor(3.5158, dtype=torch.float64)


In [129]:
c

tensor([[2., 1., 6.],
        [4., 9., 7.],
        [4., 8., 9.]])

In [142]:
print(c.view(-1,1))

tensor([[2.],
        [1.],
        [6.],
        [4.],
        [9.],
        [7.],
        [4.],
        [8.],
        [9.]])


In [151]:
print(c.view(1,-1))

tensor([[2., 1., 6., 4., 9., 7., 4., 8., 9.]])


In [152]:
r = torch.rand(4, 4)

In [153]:
r

tensor([[0.3252, 0.1441, 0.6584, 0.2393],
        [0.8958, 0.7523, 0.3619, 0.8940],
        [0.9306, 0.0242, 0.3556, 0.4580],
        [0.5152, 0.2634, 0.5732, 0.6246]])

In [155]:
print(r.dtype)

torch.float32


In [158]:
r2 =torch.randn(4, 4)

In [159]:
r2

tensor([[-0.4132, -0.2600,  0.1133,  2.0432],
        [ 1.4417, -0.2621, -0.3211, -0.7125],
        [-1.2958,  0.8487, -0.3866, -0.9811],
        [ 0.8715, -1.4206,  1.6631, -1.1985]])

In [160]:
# create an array of 5 random integers from values between 6 and 9(exlusive of 10)

In [161]:
in_array = torch.randint(6,10,(5,))

In [171]:
print(torch.numel(in_array))

5


In [163]:
print(in_array)
print(in_array.dtype)

tensor([6, 7, 6, 7, 9])
torch.int64


In [168]:
in_array2 = torch.randint(6,10,(3,3))

In [169]:
in_array2

tensor([[7, 7, 7],
        [6, 8, 8],
        [8, 8, 8]])

In [173]:
print(torch.numel(in_array2))

9


In [174]:
add_result = torch.add(r, r2)

In [175]:
add_result

tensor([[-0.0880, -0.1159,  0.7717,  2.2825],
        [ 2.3375,  0.4902,  0.0407,  0.1814],
        [-0.3653,  0.8729, -0.0310, -0.5232],
        [ 1.3866, -1.1572,  2.2363, -0.5739]])

In [176]:
r2

tensor([[-0.4132, -0.2600,  0.1133,  2.0432],
        [ 1.4417, -0.2621, -0.3211, -0.7125],
        [-1.2958,  0.8487, -0.3866, -0.9811],
        [ 0.8715, -1.4206,  1.6631, -1.1985]])

In [177]:
r

tensor([[0.3252, 0.1441, 0.6584, 0.2393],
        [0.8958, 0.7523, 0.3619, 0.8940],
        [0.9306, 0.0242, 0.3556, 0.4580],
        [0.5152, 0.2634, 0.5732, 0.6246]])

In [182]:
r2.add_(r) # modifiy dirictlly r2 
# r2 = torch.add(r,r2)

tensor([[ 0.5624,  0.1722,  2.0884,  2.7612],
        [ 4.1290,  1.9948,  0.7645,  1.9694],
        [ 1.4959,  0.9214,  0.6803,  0.3928],
        [ 2.4170, -0.6305,  3.3827,  0.6752]])

In [179]:
r2

tensor([[-0.0880, -0.1159,  0.7717,  2.2825],
        [ 2.3375,  0.4902,  0.0407,  0.1814],
        [-0.3653,  0.8729, -0.0310, -0.5232],
        [ 1.3866, -1.1572,  2.2363, -0.5739]])

In [180]:
r

tensor([[0.3252, 0.1441, 0.6584, 0.2393],
        [0.8958, 0.7523, 0.3619, 0.8940],
        [0.9306, 0.0242, 0.3556, 0.4580],
        [0.5152, 0.2634, 0.5732, 0.6246]])

In [183]:
print(r2[:, 1])

tensor([ 0.1722,  1.9948,  0.9214, -0.6305])


In [187]:
print(r2[:,:2])

tensor([[ 0.5624,  0.1722],
        [ 4.1290,  1.9948],
        [ 1.4959,  0.9214],
        [ 2.4170, -0.6305]])


In [189]:
print(r2[:,:3])

tensor([[ 0.5624,  0.1722,  2.0884],
        [ 4.1290,  1.9948,  0.7645],
        [ 1.4959,  0.9214,  0.6803],
        [ 2.4170, -0.6305,  3.3827]])


In [191]:
print(r2[:3,:]) # (column,Row)

tensor([[0.5624, 0.1722, 2.0884, 2.7612],
        [4.1290, 1.9948, 0.7645, 1.9694],
        [1.4959, 0.9214, 0.6803, 0.3928]])
